### PR TITLE
[WIP] feat(experimental): add experimental theme

### PR DESCRIPTION
**Pull request by joshblack**
This PR adds in the first pass at an experimental theme for the Carbon Design System.

Currently this PR is *not* ready, as we still have to update the values of variables in this file, and also need to investigate what additional tokens need to be added.

### CODE REVIEW

**Comment by diego-codes** [comment]
This seems like a good base to start experimental theme development.

**Comment by tw15egan** [comment]
We can also work on standardizing the theming variables, as the existing ones (outside of color) were created in a short timeframe to help out Watson adoption.

**Comment by diego-codes** [comment]
Yeah, I think it would be good to maybe do `${component-name}__{property-name}`. What do you think?

**Comment by joshblack** [comment]
Sounds good to me 😄

**Pull request closed without merging**
